use_default_settings:
  engines:
    keep_only:
      - google
      - bing
      - wikipedia

server:
  secret_key: "zoro-dev-searxng-secret"
  limiter: false
  image_proxy: false

search:
  formats:
    - html
    - json
  default_lang: "en"

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: bing
    engine: bing
    shortcut: b
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false
